### ISSUE TITLE
Add db.sqlite3 to .gitignore

### ISSUE THREAD

**Issue by sks444** [coala/community#127]
There is `.sqlite3` in the `.gitignore` but that is not ignoring `db.sqlite3`.
Change it to `db.sqlite3`.

difficulty/newcomer

**Comment by RaiVaibhav** [comment]
I think instead of changing it to `db.sqlite3` in `.gitignore` it have to besomething like `*.sqlite3` as currently it is considering `.sqlite3` as a file
