### ISSUE TITLE
Add jinja bear to .coafiles

### ISSUE THREAD

**Issue by jayvdb** [coala/community#129]
The templates are in jinja format.
We have a bear for those.

**Comment by jakethakur** [comment]
I might have a look at this. By templates, do you mean everything in the /templates folder? Or just /model/templates?

**Comment by sks444** [comment]
@jakethakur, everything in the templates folder.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [5256108693258240](https://codein.withgoogle.com/dashboard/tasks/5256108693258240).
