### ISSUE TITLE
Move fetch_deployed_data out of gci app

### ISSUE THREAD

**Issue by li-boxuan** [coala/community#132]
https://github.com/coala/community/blob/e9d74a1b5ca293683b6cbe1f71757a03a52a57ac/gci/management/commands/fetch_deployed_data.py is reusable. It should not be in the gci app directory.

**Comment by jayvdb** [comment]
Im not sure why, but it doesnt like being in the `community` app.

Maybe it looks in `INSTALLED_APPS`.
It isnt worth creating a new app for these generic commands, so I propose it be moved into the data app.

**Comment by li-boxuan** [comment]
> Im not sure why, but it doesnt like being in the community app
I also tried that and it didn't work ;)

>  I propose it be moved into the data app.
Looks good to me.
