### ISSUE TITLE
webservices is down and breaking everything

### ISSUE THREAD

**Issue by jayvdb** [coala/community#154]
The community website shouldnt fail if the webservices component is dead.

We should take advantage of it being down to fix our code so that it doesnt bring down the entire system.

**Comment by sks444** [comment]
This is happening because of [tests for `import_contributors_data`](https://github.com/coala/community/blob/5d97537bf2aa2e7914a804c15080a4ed2fa500c1/data/tests/test_management_commands.py#L15) management command;

Maybe we can think of other ways of testing management commands.

**Comment by sks444** [comment]
Or maybe figure out a way to save the old data somewhere and fetch the data from there whenever the webservices goes down next time.

**Comment by jayvdb** [comment]
first check if the real data from webservices has 0 records.
If it does, something went wrong and all tests of the real data should be skipped
