### ISSUE TITLE
Correct the typo 

### ISSUE THREAD

**Issue by shikharvaish28** [coala/community#192]
In ```gamification/process/activity_points.py```, spelling of ```tuple``` is written as ```touple```.

This can be a good new-comer issue.

**Comment by shikharvaish28** [comment]
@Tusharmalik It is a bad practice to open a PR of an issue without being assigned to it. To get yourself assigned for a particular issue please ask for it on our [gitter channel ](https://gitter.im/coala/coala).

Also, please go through our [developers guide](api.coala.io/en/latest/Developers/Newcomers_Guide.html)

**Comment by Tusharmalik** [comment]
@Shikhar Vaish I am sorry for acting so unprofessionally. I will definitely
go through developers guide
<http://api.coala.io/en/latest/Developers/Newcomers_Guide.html> once and
will ask on gitter channel <https://gitter.im/coala/coala> for the task to
be assigned to me before opening the PR in the near future. Can you please
guide me what you want me to do with the PR that I have already opened(do
you want me to close the PR or are you going to accept the PR).

**Comment by shikharvaish28** [comment]
No, don't close the PR. Just ask on the gutter channel for this task to be assigned to you. Once it's assigned to you, mention about the PR and ask for it to be reviewed.

**Comment by li-boxuan** [comment]
Unassigned due to inactivity.

**Comment by raghav9-97** [comment]
I want to take this up.Please assign me to this task.

**Comment by sanchit48** [comment]
I would like to get assigned to this issue. plz do

**Comment by orrimoch** [comment]
Hi! 
I'm new into this.
I'd like to know is there an 'newcomer' issue I can assign to?
Please it's my first time here,
Thanks,
Or

**Comment by kx-chen** [comment]
@orrimoch Check out the newcomers guide: coala.io/newcomer. There are newcomer issues here: https://coala.io/new.

**Comment by sanchit48** [comment]
Hi, i am working on this issue, once i get an invite, i will get it assigned and make a PR.
I already asked for the invite and to get this assigned on the gitter channel.
