### ISSUE TITLE
Create django data model for GCI students

### ISSUE THREAD

**Issue by jayvdb** [coala/community#2]

**Comment by sks444** [comment]
@jayvdb, I would like to work on this issue.

**Comment by jayvdb** [comment]
@sks444 , you do not appear to be a member of the coala org at the moment.  I thought you joined?  Did you leave?  If not, I'll try to find what is going wrong.

**Comment by sks444** [comment]
@jayvdb, Yes, I joined the coala one month ago at Pycon India and I didn't leave, my profile is still showing that I am the member of coala.

>  I'll try to find what is going wrong.
Sure. :)

**Comment by jayvdb** [comment]
Found the problem; sorry for the delay
