### ISSUE TITLE
OpenHub without token generates empty page

### ISSUE THREAD

**Issue by jayvdb** [coala/community#201]
If no OH_TOKEN was given during the build, the openhub/ page will be empty.

The `openhub/` page should explain how to enable the app, or the top level index page could be dynamic and place the `openhub/` link in a 'Disabled section' with a note about using tokens.

**Comment by bhawesh96** [comment]
I tried to reproduce the issue and went through the related to code.
Will it be a feasible fix if I call ```CurrentUserStore.fetchUser()``` upon clicking 'Save'. If returns ```info```, then allow Save, else, show error message in the login dialog itself?
