### ISSUE TITLE
Travis is failing on master due to andrewda/trav

### ISSUE THREAD

**Issue by li-boxuan** [coala/community#226]
Travis has been failing on master for days, the latest failure is: https://travis-ci.org/coala/community/builds/459360893

Running `.ci/build.sh` locally leads to the same error: 
```
python manage.py distill-local public --force
OH_TOKEN can not be obtained: 'Please put your OH API key at .OH_API_KEY.'
CommandError: Failed to render view:
```
which is not a very useful message (see https://github.com/mgrp/django-distill/issues/10 also)

I used `git bisect` and found out the first problematic commit was https://github.com/coala/community/pull/30/commits/98031ce058b958c1ae94fe2ae2b4d3f58c40b0d6, which introduced https://github.com/andrewda/trav as a dependency. Build succeeds when that commit is dropped.

Very likely, some updates on https://github.com/andrewda/trav lead to the Travis failure.

ping @andrewda

**Comment by kx-chen** [comment]
The most recent change to `trav` that could have caused this is likely my commit: https://github.com/andrewda/trav/commit/ce805d12d3d1db0a51b1aa26bba9cd9ecc0d96b8. Will look into it.

**Comment by kx-chen** [comment]
The issue is in `views.py` in `get_context_data` . 

With the update to trav, I unintentionally made it so that  `Travis.BUILD_WEB_URL` would have to be called with `TRAVIS.TRAVIS_BUILD_WEB_URL`, as that is the full environment variable name. 

All is good if you change `TRAVIS.BUILD_WEB_URL` to `TRAVIS.TRAVIS_BUILD_WEB_URL`. I can try to submit changes to `trav` that would fix it, but I think that's up to Andrew to decide.

**Comment by andrewda** [comment]
Ah my bad, I didn't catch the repercussions that the trav change would have here. We should probably keep the new names on trav as it's easier to adjust if Travis ever adds more/removes variables, and makes the properties aligned with environment variables. As @kx-chen said, the fix is just:

```diff
- Travis.BUILD_WEB_URL
+ Travis.TRAVIS_BUILD_WEB_URL
```

**Comment by li-boxuan** [comment]
@kx-chen Would you like to fix this issue?

**Comment by kx-chen** [comment]
Sure.
