### ISSUE TITLE
Deploy of fork to netlify fails the build

### ISSUE THREAD

**Issue by KVGarg** [coala/community#232]
Following the [instructions](https://github.com/coala/community/#deploy-netlify-on-your-fork-) to deploy the changes pushed in forked repo on netlify is failing the build.
Error log - https://gist.github.com/KVGarg/db41b5f3019513f3659dd44c014ba27c

**Comment by AkshJain99** [comment]
@KVGarg  ithink this issue is already opened by  sks444 #189 , isn't it?

**Comment by KVGarg** [comment]
I don't think, it is related to that issue. Because here the netlify build is failing due to non-availability of correct Repository URL.
Check https://gist.github.com/KVGarg/db41b5f3019513f3659dd44c014ba27c#file-community-netlify-build-L226

**Comment by AkshJain99** [comment]
okay but incoorect repository url in the sense what ??  what you think what can be the solution for this?

**Comment by KVGarg** [comment]
> what you think what can be the solution for this?

IDK, I have to debug the code to get the right solution.
Also, I think we need to provide same configuration (environment variables) that are being set while deploying new site on netlify that are already set for master branch on netlify.
Maybe we are missing some information in README.md

**Comment by KVGarg** [comment]
Maybe related to #171

**Comment by KVGarg** [comment]
While deploying a branch on netlify, following problems have been coming listed below being raised from `get_irep()` [function](https://github.com/KVGarg/community/blob/deploy_branch/community/git.py#L111)
1. [hoster](https://github.com/KVGarg/community/blob/deploy_branch/community/git.py#L115) returned as None
2. `Owner` and `Name` attributes in [url](https://github.com/KVGarg/community/blob/deploy_branch/community/git.py#L113) are None due to which error is raised from function [get_repo_slug()](https://github.com/KVGarg/community/blob/deploy_branch/community/git.py#L116)
3. [repo](https://github.com/KVGarg/community/blob/deploy_branch/community/git.py#L117) not an instance of GitHubRepository

**Comment by KVGarg** [comment]
After spending 3-4 hrs on it, finally solved that above solution :open_mouth: 
But as usual failing with building static website :disappointed:

**Comment by KVGarg** [comment]
@jayvdb Can I create a PR for this issue, if it is a valid issue?

**Comment by KVGarg** [comment]
**The local deployed branch on netlify of forked version is passing the build.** So, I guess the issue is no more valid. Maybe to due to node version up-gradation or some packages got upgraded the build is getting passed :+1+
Closing for now, until the issue rises again in future

**Comment by KVGarg** [comment]
The `git.py` needs to updated! Made changes in a pull_request created in coala-webservices!
