### ISSUE TITLE
Build failing due to latest version of django getting installed

### ISSUE THREAD

**Issue by KVGarg** [coala/community#243]
Django v2.1.7 should be installed as it depends upon Ubuntu Trusty v14.04 and makes the CI builds green. Installing latest version is leading to problems as it requires Sqlite v3.8.3 or later version which isn't available in Ubuntu Trusty. Available for now in Ubuntu Xenial image.

**Comment by jayvdb** [comment]
The solution is to use the xenial image.  Then you saw other problems with Django 2.2.  They should be documented here in this issue.

And there were problems also with Django 2.1 ?  They should be documented in a separate issue.

**Comment by KVGarg** [comment]
> xenial image. 
Using xenial image is installing later versions of py>1.5.2, pluggy>0.6.0. One of the reasons due to which build is failing when using xenial. Ubuntu xenial image has to be used if want to work with django v2.2 as it no longer supports sqlite v3.8.2

When using xenial image- 
Issues with Django v2.1.7 when pytest v4.4.0 or later is installed with it? Please refer [build](https://travis-ci.org/coala/community/jobs/532912493) 
Issues with Django v2.1.7 when pytest v3.6.4? Please refer [build](https://travis-ci.org/coala/community/jobs/532920800)
Issues with Django v2.2.1 when pytest v4.4.2? Please refer [build](https://travis-ci.org/KVGarg/community/jobs/532835986)
