### ISSUE TITLE
Progress of solving & creating issues

### ISSUE THREAD

**Issue by LifetimeAlone** [coala/community#25]
Website may include a bar chart widget, which will show the dynamics of solving & creating issues. It will highlight how active the community has been during periods of time. 
The X-axis of the chart will be timeline (e.g. last 5 month), and Y-axis - amount of issues solved and created. To be visually intuitive, created & solved issues should be marked with different colors. Also, dates with positive tendency (rise in activity) may be marked green, dates with negative tendency - red.
Tools:
Bar chart creation: http://www.chartjs.org or https://d3js.org
Fetching data: IGitt has issue searching func. For each repo of the org, we can search issues by last update date and status (it must be closed).

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by nalinbhardwaj** [comment]
Probably a bit of an opinion, but I feel a line chart may be better for data representation?
Since we are trying to visualise change as well, and that would eliminate the need for a color for dates, making the graph more clearer.
