### ISSUE TITLE
Remove 'coala' from COMMIT_AUTHOR_EMAIL

### ISSUE THREAD

**Issue by jayvdb** [coala/community#29]
`.travis.yml` currently sets `COMMIT_AUTHOR_EMAIL: "nobody@coala.io"` , but that violates this repositories rule that 'coala' shouldnt be mentioned anywhere.

One approach is to use a generic email address.
Another is to use the git remote info to find the GitHub org (#26), and then derive an email address from the GitHub org.

**Comment by andrewda** [comment]
I think the best we can do here w/o making a GitHub API call is to do something like `nobody@{org}.com`, but it might not be the best idea to try and guess the org domain if we're going to be wrong 90% of the time. It's probably better to use something like `ghost@github.com` or `{org}@example.com`.

**Comment by nalinbhardwaj** [comment]
@jayvdb this was closed in PR #27 only partially. Should I make another PR just changing the email to something generic like `CI@travis.com`, or something like @andrewda suggested..
