### ISSUE TITLE
Not rendering HTML code

### ISSUE THREAD

**Issue by ashwini0529** [coala/community#31]
The student profile section isn't rendering the HTML code.

<img width="417" alt="screen shot 2017-12-08 at 9 36 01 am" src="https://user-images.githubusercontent.com/8419333/33750619-425b4a66-dbfb-11e7-888b-b5cbde232935.png">

**Comment by andrewda** [comment]
Are there any errors in your console?

**Comment by blazeu** [comment]
No errors.

![image](https://user-images.githubusercontent.com/1438859/33754525-2c14a0e4-dc1f-11e7-8d26-ff3e5ce21ec1.png)
![image](https://user-images.githubusercontent.com/1438859/33754545-3e4e8234-dc1f-11e7-9b6b-f363cf029790.png)

**Comment by jayvdb** [comment]
It is all going to be rewritten after #13 .  Ideally the widgets are rendered during the build process.

**Comment by ashwini0529** [comment]
Works good. Closing the issue! 😄
