### ISSUE TITLE
Proper documention

### ISSUE THREAD

**Issue by ashwini0529** [coala/community#38]
A proper documentation with installation guide could help a lot to setup locally and contribute.

**Comment by jayvdb** [comment]
This is changing a lot at the moment.
I've done one largish improvement to the build system, which partially gets the django stuff neatened.
We've just to choose the front-end toolset, which will have a large impact on any documenation.

**Comment by ashwini0529** [comment]
Closing issue as of now. Will reopen once it gets a shape.
