### ISSUE TITLE
Create a config file to manage organisation details

### ISSUE THREAD

**Issue by ashwini0529** [coala/community#51]
We're facing a lot of issues right now because of config files. Creating a config file is required to maintain details like `org_name`, `twitter handle`, `website link` etc that could be used further.

**Comment by jayvdb** [comment]
Where are you going to put the config file?
it can not go into the repository, otherwise it makes forks un-mergable.

**Comment by jayvdb** [comment]
Also we already have values for all of those examples you have provided, and some of them are already available in the django layer.
Closing until you have provided a real reason why we need a config file.
