### ISSUE TITLE
Use global setting for GCI data directory variable in gci app.

### ISSUE THREAD

**Issue by pradeepgangwar** [coala/community#71]
Currently in https://github.com/coala/community/blob/master/gci/config.py#L6 we define GCI_DATA_DIRECTORY locally using python file management system. Since there is global setting to use this specified [here](https://github.com/coala/community/blob/master/community/settings.py#L120). So we want to replace that to use the global setting.

label difficulty/low newcomer

**Comment by Kagamihime** [comment]
Hello,

I would like to know if the only thing to do would be to use `STATIC_ROOT` at https://github.com/coala/community/blob/master/gci/config.py#L8 ? Or is it about something else?

If so, I would like to be assigned to this issue please.

**Comment by Dragneel7** [comment]
Hi, I would like to work on this issue. Can I proceed?

**Comment by joaomcarvalho** [comment]
Hi, I would like to help, can I work on this issue?

**Comment by Makman2** [comment]
@Dragneel7 sorry for missing you, I've sent an invite, please accept :+1:

@joaomcarvalho I would assign you the other newcomer issue you've been pinging on ;)

**Comment by vaib10sai** [comment]
Hi, can I get this issue assigned? :)
