### ISSUE TITLE
graphs not loading at http://community.coala.io/activity/

### ISSUE THREAD

**Issue by ashwini0529** [coala/community#72]
<img width="1280" alt="screen shot 2018-01-10 at 7 41 13 pm" src="https://user-images.githubusercontent.com/8419333/34776948-98c0d346-f63e-11e7-963d-353baa7fe5ab.png">

**Comment by nalinbhardwaj** [comment]
Seems to be an issue with [coala/gh-board](https://github.com/coala/gh-board), [issues.json](https://coala.github.io/gh-board/issues.json) is no longer being fetched. I don't know much about it, but seems related to [this promise rejection](https://travis-ci.org/coala/gh-board/builds/330671707#L3030).
Ping @blazeu.

**Comment by ashwini0529** [comment]
Still the same :/
@blazeu  @jayvdb

**Comment by ashwini0529** [comment]
Activity Data is empty. 
http://community.coala.io/static/activity-data.json

**Comment by KVGarg** [comment]
Graph is loading in Linux
![image](https://user-images.githubusercontent.com/35761292/51763181-e3a89d00-20f7-11e9-8c20-f07f78b7a9ca.png)

**Comment by KVGarg** [comment]
Graph is getting displayed in Linux
![screenshot from 2019-01-25 23-21-45](https://user-images.githubusercontent.com/35761292/51763321-5285f600-20f8-11e9-93eb-c4224d8f83b7.png)

@ashwini0529 In which OS and browser were you facing this issue?

**Comment by KVGarg** [comment]
> Activity Data is empty.
> http://community.coala.io/static/activity-data.json

Please can you re-check this, because when I opened that link the response is being received

**Comment by ashwini0529** [comment]
It works now. 😄
