### ISSUE TITLE
Uncached netlify builds using python 2.7

### ISSUE THREAD

**Issue by jayvdb** [coala/community#85]
```
1:13:24 AM: /usr/local/bin/run-build-functions.sh: line 150: /opt/buildhome/python3.6.2/bin/activate: No such file or directory
1:13:24 AM: Error setting python version from runtime.txt
1:13:24 AM: Will use default version (2.7)
```
https://app.netlify.com/sites/coala-community/deploys/5aa17d3e92226a6064ec5772

**Comment by sks444** [comment]
@jayvdb, Why the build is not running on python3.6.2?

**Comment by sks444** [comment]
@jayvdb, I remember the solution in my dream :P 
Because I have already seen @Makman2 correcting that error here https://github.com/coala/documentation/blob/master/runtime.txt

Let me do it :)
