### ISSUE TITLE
Use generic ListView

### ISSUE THREAD

**Issue by jayvdb** [coala/community#87]
We can make use of the generic ListView to provide a default viewer of datasets that we are importing.

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

**Comment by sks444** [comment]
https://gitter.im/coala/community?at=5aa35d5c53c1dbb743c52b85
Just for more understanding of the issue.

**Comment by sks444** [comment]
https://github.com/jieter/django-tables2
Is it good for this?
