### ISSUE TITLE
Use logging

### ISSUE THREAD

**Issue by jayvdb** [coala/community#9]
Instead of print statements to the travis log, problems should be logged properly and a view generated with the logs.

**Comment by abhinavralhan** [comment]
I would like to take this up @jayvdb . Any pointers how to get started ?

**Comment by jayvdb** [comment]
I suggest using https://pypi.python.org/pypi/django-modelhandler to put the logging into a model , and then create a simple single page app that displays the data in the db.

**Comment by seeeturtle** [comment]
thanks @jayvdb? I'll try it :)
